/*
 * Topic-derivation expectations in this file were generated by running the
 * Node SDK's `mqttTopicsForIdentity` / `mqttConnectionEndpoint`
 * (dist/src/transport-mqtt.js) against the same credential sets.
 */
#include "harness.h"
#include "thalovant/topics.h"

static thalovant_identity base_identity(void)
{
    thalovant_identity identity;
    memset(&identity, 0, sizeof(identity));
    strcpy(identity.access_key, "tlv-key-123");
    strcpy(identity.password, "pw");
    strcpy(identity.site_id, "kitchen");
    strcpy(identity.default_master, "https://hub.example.com");
    identity.default_port = 5679;
    identity.mqtt.present = true;
    strcpy(identity.mqtt.endpoint, "mqtt://broker.local");
    strcpy(identity.mqtt.username, "hub-user");
    strcpy(identity.mqtt.password, "pw");
    identity.mqtt.qos = 1;
    return identity;
}

static void check_topics(const thalovant_identity *identity, const char *c2s, const char *s2c,
                         const char *status)
{
    thalovant_mqtt_topics topics;
    CHECK_INT_EQ(thalovant_mqtt_topics_derive(identity, &topics), THALOVANT_OK);
    CHECK_STR_EQ(topics.c2s, c2s);
    CHECK_STR_EQ(topics.s2c, s2c);
    CHECK_STR_EQ(topics.status, status);
}

static void test_prefix_plain(void)
{
    thalovant_identity identity = base_identity();
    strcpy(identity.mqtt.topic_prefix, "hivemind/hub-1");
    check_topics(&identity, "hivemind/hub-1/c2s/tlv-key-123", "hivemind/hub-1/s2c/tlv-key-123",
                 "hivemind/hub-1/status/tlv-key-123");
}

static void test_prefix_trailing_satellite_dropped(void)
{
    thalovant_identity identity = base_identity();
    strcpy(identity.mqtt.topic_prefix, "/hivemind/hub-1/tlv-key-123/");
    check_topics(&identity, "hivemind/hub-1/c2s/tlv-key-123", "hivemind/hub-1/s2c/tlv-key-123",
                 "hivemind/hub-1/status/tlv-key-123");
}

static void test_prefix_trailing_username_dropped(void)
{
    thalovant_identity identity = base_identity();
    strcpy(identity.mqtt.topic_prefix, "hivemind/hub-1/hub-user");
    check_topics(&identity, "hivemind/hub-1/c2s/tlv-key-123", "hivemind/hub-1/s2c/tlv-key-123",
                 "hivemind/hub-1/status/tlv-key-123");
}

static void test_prefix_naming_a_topic(void)
{
    thalovant_identity identity = base_identity();
    strcpy(identity.mqtt.topic_prefix, "custom/base/c2s/dev-7");
    check_topics(&identity, "custom/base/c2s/dev-7", "custom/base/s2c/dev-7",
                 "custom/base/status/dev-7");
    strcpy(identity.mqtt.topic_prefix, "custom/base/s2c/dev-7");
    check_topics(&identity, "custom/base/c2s/dev-7", "custom/base/s2c/dev-7",
                 "custom/base/status/dev-7");
}

static void test_hub_id_only(void)
{
    thalovant_identity identity = base_identity();
    strcpy(identity.mqtt.hub_id, "/hub-9/");
    check_topics(&identity, "hivemind/hub-9/c2s/tlv-key-123", "hivemind/hub-9/s2c/tlv-key-123",
                 "hivemind/hub-9/status/tlv-key-123");
}

static void test_prefix_plus_hub(void)
{
    thalovant_identity identity = base_identity();
    strcpy(identity.mqtt.topic_prefix, "site/prefix");
    strcpy(identity.mqtt.hub_id, "hub-2");
    check_topics(&identity, "site/prefix/hub-2/c2s/tlv-key-123",
                 "site/prefix/hub-2/s2c/tlv-key-123", "site/prefix/hub-2/status/tlv-key-123");
    /* hub already present as a segment: not appended again */
    strcpy(identity.mqtt.topic_prefix, "site/hub-2/things");
    check_topics(&identity, "site/hub-2/things/c2s/tlv-key-123",
                 "site/hub-2/things/s2c/tlv-key-123", "site/hub-2/things/status/tlv-key-123");
}

static void test_explicit_topics(void)
{
    thalovant_identity identity = base_identity();
    strcpy(identity.mqtt.c2s_topic, "a/b/c2s/x");
    strcpy(identity.mqtt.s2c_topic, "a/b/s2c/x");
    check_topics(&identity, "a/b/c2s/x", "a/b/s2c/x", "a/b/status/x");
    strcpy(identity.mqtt.status_topic, "custom/status");
    check_topics(&identity, "a/b/c2s/x", "a/b/s2c/x", "custom/status");
}

static void test_hashed_satellite_id(void)
{
    thalovant_identity identity = base_identity();
    strcpy(identity.mqtt.topic_prefix, "hivemind/hub-1");
    identity.mqtt.hash_topics = true;
    /* sha256("tlv-key-123") first 16 hex chars, from the Node SDK. */
    check_topics(&identity, "hivemind/hub-1/c2s/17248843d394af83",
                 "hivemind/hub-1/s2c/17248843d394af83",
                 "hivemind/hub-1/status/17248843d394af83");
}

static void test_missing_configuration(void)
{
    thalovant_identity identity = base_identity();
    thalovant_mqtt_topics topics;
    CHECK_INT_EQ(thalovant_mqtt_topics_derive(&identity, &topics), THALOVANT_ERR_MISSING);
    identity.mqtt.present = false;
    CHECK_INT_EQ(thalovant_mqtt_topics_derive(&identity, &topics), THALOVANT_ERR_MISSING);
}

static void test_endpoint(void)
{
    thalovant_identity identity = base_identity();
    char endpoint[THALOVANT_MQTT_ENDPOINT_MAX];
    CHECK(thalovant_mqtt_endpoint(&identity.mqtt, endpoint, sizeof(endpoint)) > 0);
    CHECK_STR_EQ(endpoint, "mqtt://broker.local");
    /* tls upgrades the scheme and a trailing '/' is stripped. */
    strcpy(identity.mqtt.endpoint, "mqtt://broker.local:1883/");
    identity.mqtt.tls = true;
    CHECK(thalovant_mqtt_endpoint(&identity.mqtt, endpoint, sizeof(endpoint)) > 0);
    CHECK_STR_EQ(endpoint, "mqtts://broker.local:1883");
    /* Already-secure endpoints are untouched. */
    strcpy(identity.mqtt.endpoint, "mqtts://mqtt.example.com:8883");
    CHECK(thalovant_mqtt_endpoint(&identity.mqtt, endpoint, sizeof(endpoint)) > 0);
    CHECK_STR_EQ(endpoint, "mqtts://mqtt.example.com:8883");
}

static void test_endpoint_parse(void)
{
    thalovant_endpoint parsed;
    CHECK_INT_EQ(thalovant_endpoint_parse("mqtts://mqtt.example.com:8883", &parsed), THALOVANT_OK);
    CHECK_STR_EQ(parsed.scheme, "mqtts");
    CHECK_STR_EQ(parsed.host, "mqtt.example.com");
    CHECK_INT_EQ(parsed.port, 8883);
    CHECK(parsed.tls);
    CHECK_INT_EQ(thalovant_endpoint_parse("mqtt://broker.local", &parsed), THALOVANT_OK);
    CHECK_INT_EQ(parsed.port, 1883);
    CHECK(!parsed.tls);
    CHECK_INT_EQ(thalovant_endpoint_parse("wss://hub.example.com/ws?x=1", &parsed), THALOVANT_OK);
    CHECK_STR_EQ(parsed.host, "hub.example.com");
    CHECK_INT_EQ(parsed.port, 443);
    CHECK_STR_EQ(parsed.path, "/ws?x=1");
    CHECK(parsed.tls);
    CHECK_INT_EQ(thalovant_endpoint_parse("mqtt://[::1]:1884", &parsed), THALOVANT_OK);
    CHECK_STR_EQ(parsed.host, "::1");
    CHECK_INT_EQ(parsed.port, 1884);
    CHECK_INT_EQ(thalovant_endpoint_parse("no-scheme", &parsed), THALOVANT_ERR_INVALID);
}

static void test_client_id(void)
{
    char client_id[64];
    CHECK(thalovant_mqtt_client_id("tlv key!123", client_id, sizeof(client_id)) > 0);
    CHECK_STR_EQ(client_id, "thalovant-tlv-key-123");
    CHECK_INT_EQ(thalovant_mqtt_client_id("", client_id, sizeof(client_id)),
                 THALOVANT_ERR_MISSING);
    /* Truncated to 48 key characters. */
    char long_key[80];
    memset(long_key, 'a', sizeof(long_key) - 1);
    long_key[sizeof(long_key) - 1] = '\0';
    int len = thalovant_mqtt_client_id(long_key, client_id, sizeof(client_id));
    CHECK_INT_EQ(len, 10 + 48);
}

void tlv_test_topics(void)
{
    test_prefix_plain();
    test_prefix_trailing_satellite_dropped();
    test_prefix_trailing_username_dropped();
    test_prefix_naming_a_topic();
    test_hub_id_only();
    test_prefix_plus_hub();
    test_explicit_topics();
    test_hashed_satellite_id();
    test_missing_configuration();
    test_endpoint();
    test_endpoint_parse();
    test_client_id();
}
