"""Render checked-in Node JSON as C constants; no crypto implementation here."""
import json
from pathlib import Path
root = Path(__file__).resolve().parents[1]
v = json.loads((root/'tests/fixtures/noise-node.json').read_text())
lines = ['/* Generated by tools/noise-fixture-header.py from noise-node.json. */', '#ifndef TLV_NOISE_FIXTURE_H', '#define TLV_NOISE_FIXTURE_H', '#include <stddef.h>']
for k in ('psk','static_i','static_r','ephemeral_i','ephemeral_r','public_i','public_r'):
    lines.append(f'static const char *fixture_{k} = {json.dumps(v[k])};')
lines += ['typedef struct { const char *prologue; const char *messages[3]; const char *payloads[3]; const char *transport_i[3]; const char *transport_r[3]; const char *plaintexts[3]; } noise_vector;', 'static const noise_vector noise_vectors[] = {']
for exchange in v['exchanges']:
    if exchange['suite'] != '25519_AESGCM_SHA256': continue
    fields = [json.dumps(exchange['prologue'])]
    for key in ('messages','payloads','transport_i','transport_r','plaintexts'):
        values = exchange[key] + [None] * (3-len(exchange[key]))
        fields.append('{'+','.join('NULL' if x is None else json.dumps(x) for x in values)+'}')
    lines.append('{'+',\n'.join(fields)+'},')
lines += ['};','#endif']
(root/'tests/fixtures/noise-node.h').write_text('\n'.join(lines)+'\n')
